global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: simple_server
    basic_auth:
      username: admin
      password: admin
    static_configs:
      - targets: ['host.docker.internal:8081']
